import { PrismaClient, Prisma } from '@prisma/client';
import bcrypt from 'bcryptjs';

// Prisma CLI dışında (tsx ile doğrudan) çalıştırıldığında .env okunmaz;
// bu yüzden veritabanı yolunu burada garantiye alıyoruz.
// Göreli yol schema.prisma klasörüne (packages/database/prisma) göre çözülür.
if (!process.env.DATABASE_URL) process.env.DATABASE_URL = 'file:./millwal.db';

const prisma = new PrismaClient();

/* ------------------------------------------------------------------ */
/*  Kategoriler                                                        */
/* ------------------------------------------------------------------ */
const categories: Array<[string, string, string, string, string]> = [
  ['Araba', 'Araba', 'araba',
    'Sedan, hatchback, station wagon, SUV ve crossover otomobil seçenekleri.',
    'Şehir içi günlük kullanımdan uzun yol seyahatlerine kadar her ihtiyaca uygun gerçek marka ve model otomobiller. Ekonomik sınıftan SUV, üst segment ve elektrikli modellere kadar geniş bir yelpaze sunuyoruz.'],
  ['Motor', 'Motor', 'motor',
    'Şehir içi ulaşım ve gezi amaçlı motosiklet ve scooter seçenekleri.',
    'Trafikte zaman kaybetmeden hareket etmek isteyenler için şehir motosikletleri, naked modeller ve scooter seçenekleri.'],
  ['Tekne', 'Tekne', 'tekne',
    'Günübirlik deniz keyfi için sürat teknesi ve bowrider seçenekleri.',
    'Koy turları, günübirlik geziler ve özel organizasyonlar için kaptanlı veya kaptansız tekne kiralama seçenekleri.'],
  ['Jetski', 'Jetski', 'jetski',
    'Yüksek tempolu deniz deneyimi için jetski kiralama.',
    'Saatlik ve günlük jetski kiralama seçenekleri; can yeleği ve temel eğitim dahildir.'],
  ['Atv', 'Atv', 'atv',
    'Arazi sürüşüne uygun güçlü dört tekerlekli araçlar.',
    'Orman, toprak ve engebeli arazide kullanım için 4x4 çekişli ATV modelleri.'],
  ['Ticari', 'Ticari', 'ticari',
    'Hafif ticari araç, kamyonet ve yüksek hacimli panelvan çözümleri.',
    'Şehir içi dağıtım, esnaf kullanımı, saha operasyonları ve yüksek hacimli nakliye için geniş ticari araç ve pickup seçenekleri.'],
];

/* ------------------------------------------------------------------ */
/*  Yardımcılar                                                        */
/* ------------------------------------------------------------------ */
const lines = (...items: string[]) => items.join('\n');

const STD_SAFETY = lines('ABS ve EBD', 'ESP sürüş dengeleme', 'Hava yastıkları', 'Lastik basınç uyarısı', 'ISOFIX çocuk koltuğu bağlantısı', 'Acil fren asistanı');
const STD_TECH = lines('Dokunmatik multimedya ekranı', 'Apple CarPlay & Android Auto', 'Bluetooth bağlantı', 'USB şarj noktaları', 'Direksiyondan kumanda');

type V = Omit<Prisma.VehicleCreateInput, 'category'> & { categorySlug: string; gallery?: string[] };

const art = (slug: string) => `/fleet/${slug}.jpg`;

/* ------------------------------------------------------------------ */
/*  Araçlar                                                            */
/* ------------------------------------------------------------------ */
const vehicles: V[] = [
  /* ---------------------------------------------------- BİNEK OTOMOBİL */
  {
    categorySlug: 'araba', name: 'Fiat Egea Sedan', slug: 'fiat-egea', brand: 'Fiat', model: 'Egea', version: 'Urban 1.3 Multijet',
    year: 2025, badge: 'POPÜLER', segment: 'Ekonomik', bodyType: 'Sedan', color: 'Beyaz',
    shortDescription: 'Ekonomik yakıt tüketimi ve 520 litrelik bagajıyla uzun dönem kiralamanın favorisi.',
    description: 'Fiat Egea Sedan, düşük yakıt tüketimi ve geniş iç hacmiyle hem şehir içi hem şehirler arası kullanımda dengeli bir seçim sunar. 1.3 litrelik Multijet dizel motor, 100 kilometrede ortalama 4,4 litre tüketimle işletme maliyetini düşük tutar.',
    highlightText: 'Uzun dönem kurumsal kiralamalarda en çok tercih edilen modelimiz; yedek parça bulunabilirliği ve servis ağı sayesinde araç kullanılamazlık süresi minimumdadır.',
    seatCount: 5, doorCount: 4, trunkCapacity: 520, luggageCapacity: '2 büyük + 2 kabin valizi',
    fuelType: 'Dizel', transmission: 'Manuel', gearCount: 6, driveType: 'Önden Çekiş',
    engine: '1.3 Multijet', engineVolume: 1248, enginePower: 95, torque: 200, acceleration: 12.9, topSpeed: 178,
    fuelConsumption: 4.4, tankCapacity: 50, emissionClass: 'Euro 6D', co2Emission: 117,
    lengthMm: 4532, widthMm: 1729, heightMm: 1497, curbWeight: 1265,
    safetyFeatures: STD_SAFETY, techFeatures: STD_TECH,
    comfortFeatures: lines('Manuel klima', 'Elektrikli ön camlar', 'Yükseklik ayarlı sürücü koltuğu', 'Katlanabilir arka koltuk'),
    exteriorFeatures: lines('16" jant', 'Gövde renginde tamponlar', 'Elektrikli ayna'),
    hasAirConditioning: true, hasBluetooth: true, hasIsofix: true, hasParkingSensor: true,
    dailyPrice: 1500, weeklyPrice: 9500, monthlyPrice: 34000, deposit: 5000, extraKmPrice: 6,
    dailyKmLimit: 300, monthlyKmLimit: 4000, minDriverAge: 21, minLicenseYears: 1,
    insuranceInfo: 'Zorunlu trafik sigortası ve kasko dahildir. Muafiyet tutarı 7.500 ₺ olarak uygulanır.',
    fuelPolicy: 'Araç dolu depo teslim edilir, dolu depo iade edilmesi beklenir.',
    deliveryInfo: 'İstanbul Anadolu Yakası içinde ücretsiz teslimat yapılır.',
    featured: true, budgetFriendly: true, showOnHomepage: true, sortOrder: 1, rating: 4.7, reviewCount: 38,
    mainImage: art('fiat-egea'), seoTitle: 'Kiralık Fiat Egea Sedan | Günlük ve Aylık Fiyatlar',
  },
  {
    categorySlug: 'araba', name: 'Renault Clio', slug: 'renault-clio', brand: 'Renault', model: 'Clio', version: 'Touch 1.0 TCe',
    year: 2025, segment: 'Ekonomik', bodyType: 'Hatchback', color: 'Beyaz',
    shortDescription: 'Kompakt gövdesi ve otomatik vitesiyle şehir içi kullanımda pratik çözüm.',
    description: 'Renault Clio; kompakt boyutları, otomatik vitesi ve modern sürüş destek sistemleriyle şehir içi kullanımda kolaylık sağlar. Dar sokaklarda park kolaylığı ve düşük yakıt tüketimi öne çıkan avantajlarıdır.',
    seatCount: 5, doorCount: 5, trunkCapacity: 391, luggageCapacity: '1 büyük + 2 kabin valizi',
    fuelType: 'Benzin', transmission: 'Otomatik', gearCount: 7, driveType: 'Önden Çekiş',
    engine: '1.0 TCe', engineVolume: 999, enginePower: 90, torque: 160, acceleration: 12.2, topSpeed: 180,
    fuelConsumption: 5.3, tankCapacity: 42, emissionClass: 'Euro 6D', co2Emission: 121,
    lengthMm: 4053, widthMm: 1798, heightMm: 1440, curbWeight: 1177,
    safetyFeatures: STD_SAFETY, techFeatures: STD_TECH,
    comfortFeatures: lines('Otomatik klima', 'Geri görüş kamerası', 'Park sensörü', 'Hız sabitleyici'),
    exteriorFeatures: lines('LED farlar', '16" alaşım jant', 'Gündüz farları'),
    hasAirConditioning: true, hasReverseCamera: true, hasParkingSensor: true, hasCruiseControl: true, hasBluetooth: true,
    dailyPrice: 1650, weeklyPrice: 10500, monthlyPrice: 37000, deposit: 5000, extraKmPrice: 6.5,
    dailyKmLimit: 300, monthlyKmLimit: 4000,
    featured: true, budgetFriendly: true, showOnHomepage: true, sortOrder: 2, rating: 4.6, reviewCount: 27,
    mainImage: art('renault-clio'), seoTitle: 'Kiralık Renault Clio Otomatik | Millwal',
  },
  {
    categorySlug: 'araba', name: 'Hyundai i20', slug: 'hyundai-i20', brand: 'Hyundai', model: 'i20', version: 'Jump 1.4 MPI',
    year: 2024, segment: 'Ekonomik', bodyType: 'Hatchback', color: 'Gri',
    shortDescription: 'Ferah iç hacmi ve düşük işletme maliyetiyle ekonomik sınıfın dengeli seçeneği.',
    description: 'Hyundai i20, sınıfının üzerinde iç hacim sunan tasarımı ve donanım seviyesiyle günlük kullanımda konforlu bir deneyim sağlar. Otomatik şanzıman seçeneği şehir içi trafikte sürüş yorgunluğunu azaltır.',
    seatCount: 5, doorCount: 5, trunkCapacity: 352,
    fuelType: 'Benzin', transmission: 'Otomatik', gearCount: 6, driveType: 'Önden Çekiş',
    engine: '1.4 MPI', engineVolume: 1368, enginePower: 100, torque: 134, acceleration: 12.7, topSpeed: 185,
    fuelConsumption: 6.5, tankCapacity: 40, emissionClass: 'Euro 6D',
    lengthMm: 4040, widthMm: 1775, heightMm: 1450,
    safetyFeatures: STD_SAFETY, techFeatures: STD_TECH,
    comfortFeatures: lines('Otomatik klima', 'Geri görüş kamerası', 'Direksiyondan kumanda'),
    hasAirConditioning: true, hasReverseCamera: true, hasBluetooth: true,
    dailyPrice: 1450, weeklyPrice: 9200, monthlyPrice: 32500, deposit: 5000, dailyKmLimit: 300,
    budgetFriendly: true, showOnHomepage: true, sortOrder: 3, rating: 4.5, reviewCount: 19,
    mainImage: art('hyundai-i20'),
  },
  {
    categorySlug: 'araba', name: 'Renault Megane Sedan', slug: 'renault-megane', brand: 'Renault', model: 'Megane', version: 'Icon 1.5 Blue dCi EDC',
    year: 2025, segment: 'Orta Sınıf', bodyType: 'Sedan', color: 'Lacivert',
    shortDescription: 'Uzun yol konforu ve düşük dizel tüketimiyle şehirler arası kullanımın tercihi.',
    description: 'Renault Megane Sedan, 1.5 litrelik Blue dCi motoru ve EDC çift kavramalı şanzımanıyla uzun yolda hem sessiz hem ekonomik bir sürüş sunar. Geniş arka diz mesafesi, dört kişilik seyahatlerde konfor sağlar.',
    seatCount: 5, doorCount: 4, trunkCapacity: 508,
    fuelType: 'Dizel', transmission: 'Otomatik', gearCount: 7, driveType: 'Önden Çekiş',
    engine: '1.5 Blue dCi', engineVolume: 1461, enginePower: 115, torque: 260, acceleration: 11.2, topSpeed: 195,
    fuelConsumption: 4.2, tankCapacity: 47, emissionClass: 'Euro 6D', co2Emission: 112,
    lengthMm: 4632, widthMm: 1814, heightMm: 1447, curbWeight: 1350,
    safetyFeatures: lines(STD_SAFETY, 'Şerit takip sistemi', 'Kör nokta uyarısı'),
    techFeatures: lines(STD_TECH, 'Navigasyon', 'Dijital gösterge paneli'),
    comfortFeatures: lines('Çift bölgeli otomatik klima', 'Geri görüş kamerası', 'Adaptif hız sabitleyici', 'Anahtarsız giriş'),
    exteriorFeatures: lines('Full LED farlar', '17" alaşım jant', 'Krom detaylar'),
    hasAirConditioning: true, hasNavigation: true, hasReverseCamera: true, hasParkingSensor: true, hasCruiseControl: true,
    dailyPrice: 2100, weeklyPrice: 13300, monthlyPrice: 47000, deposit: 7500, extraKmPrice: 8,
    dailyKmLimit: 350, monthlyKmLimit: 5000, minDriverAge: 23,
    featured: true, showOnHomepage: true, sortOrder: 4, rating: 4.8, reviewCount: 22,
    mainImage: art('renault-megane'),
  },
  {
    categorySlug: 'araba', name: 'Toyota Corolla Hybrid', slug: 'toyota-corolla-hybrid', brand: 'Toyota', model: 'Corolla', version: 'Dream 1.8 Hybrid e-CVT',
    year: 2025, badge: 'HİBRİT', segment: 'Orta Sınıf', bodyType: 'Sedan', color: 'Gümüş',
    shortDescription: 'Şehir içinde 4 litrenin altına inen tüketimiyle işletme maliyetini ciddi şekilde düşürür.',
    description: 'Toyota Corolla Hybrid, elektrik motoru ve benzinli ünitenin birlikte çalıştığı sistemi sayesinde özellikle şehir içi kullanımda çok düşük yakıt tüketimi sağlar. Şarj gerektirmez; sistem frenleme sırasında kendini şarj eder.',
    highlightText: 'Yoğun şehir içi kullanımı olan filolarda yakıt maliyetini benzinli eşdeğerine göre belirgin şekilde azaltır.',
    seatCount: 5, doorCount: 4, trunkCapacity: 470,
    fuelType: 'Hibrit', transmission: 'Otomatik', driveType: 'Önden Çekiş',
    engine: '1.8 Hybrid', engineVolume: 1798, enginePower: 140, torque: 185, acceleration: 10.9, topSpeed: 180,
    fuelConsumption: 3.9, tankCapacity: 43, batteryCapacity: 1.3, emissionClass: 'Euro 6D', co2Emission: 89,
    lengthMm: 4630, widthMm: 1780, heightMm: 1435, curbWeight: 1420,
    safetyFeatures: lines(STD_SAFETY, 'Toyota Safety Sense', 'Şerit takip ve yönlendirme', 'Yaya algılamalı fren'),
    techFeatures: lines(STD_TECH, 'Navigasyon', 'Kablosuz şarj'),
    comfortFeatures: lines('Çift bölgeli otomatik klima', 'Adaptif hız sabitleyici', 'Isıtmalı ön koltuklar', 'Geri görüş kamerası'),
    exteriorFeatures: lines('Full LED farlar', '17" alaşım jant'),
    hasAirConditioning: true, hasNavigation: true, hasReverseCamera: true, hasParkingSensor: true, hasCruiseControl: true,
    dailyPrice: 2450, weeklyPrice: 15500, monthlyPrice: 54000, deposit: 8000, extraKmPrice: 9,
    dailyKmLimit: 350, minDriverAge: 23,
    featured: true, showOnHomepage: true, sortOrder: 5, rating: 4.9, reviewCount: 31,
    mainImage: art('toyota-corolla-hybrid'), seoTitle: 'Kiralık Toyota Corolla Hybrid | Düşük Tüketim',
  },
  {
    categorySlug: 'araba', name: 'Volkswagen Passat', slug: 'volkswagen-passat', brand: 'Volkswagen', model: 'Passat', version: 'Business 2.0 TDI DSG',
    year: 2025, segment: 'Üst Sınıf', bodyType: 'Sedan', color: 'Antrasit',
    shortDescription: 'Yönetici transferleri ve uzun yol için sessiz, güçlü ve prestijli bir sedan.',
    description: 'Volkswagen Passat, 2.0 TDI motoru ve DSG şanzımanıyla uzun yolda üst düzey sürüş konforu sunar. Geniş bagaj hacmi ve arka diz mesafesi, yönetici transferlerinde ve iş seyahatlerinde tercih edilmesini sağlar.',
    seatCount: 5, doorCount: 4, trunkCapacity: 586,
    fuelType: 'Dizel', transmission: 'Otomatik', gearCount: 7, driveType: 'Önden Çekiş',
    engine: '2.0 TDI', engineVolume: 1968, enginePower: 150, torque: 360, acceleration: 8.9, topSpeed: 223,
    fuelConsumption: 4.8, tankCapacity: 66, emissionClass: 'Euro 6D', co2Emission: 126,
    lengthMm: 4917, widthMm: 1852, heightMm: 1477, curbWeight: 1560,
    safetyFeatures: lines(STD_SAFETY, 'Şerit takip sistemi', 'Kör nokta uyarısı', 'Yorgunluk tespit sistemi', 'Adaptif fren asistanı'),
    techFeatures: lines(STD_TECH, 'Navigasyon', 'Dijital kokpit', 'Kablosuz şarj', 'Premium ses sistemi'),
    comfortFeatures: lines('3 bölgeli otomatik klima', 'Elektrikli koltuk ayarı', 'Isıtmalı koltuklar', 'Anahtarsız giriş ve çalıştırma', 'Adaptif hız sabitleyici'),
    exteriorFeatures: lines('Matrix LED farlar', '18" alaşım jant', 'Elektrikli bagaj kapağı'),
    hasAirConditioning: true, hasNavigation: true, hasReverseCamera: true, hasParkingSensor: true,
    hasCruiseControl: true, hasLeatherSeats: true,
    dailyPrice: 3900, weeklyPrice: 24500, monthlyPrice: 86000, deposit: 15000, extraKmPrice: 14,
    dailyKmLimit: 350, minDriverAge: 27, minLicenseYears: 3,
    insuranceInfo: 'Kasko ve trafik sigortası dahildir. Üst segment araçlarda muafiyet 15.000 ₺ olarak uygulanır.',
    featured: true, showOnHomepage: true, sortOrder: 6, rating: 4.9, reviewCount: 16,
    mainImage: art('volkswagen-passat'),
  },
  {
    categorySlug: 'araba', name: 'Audi A4', slug: 'audi-a4', brand: 'Audi', model: 'A4', version: 'Advanced 35 TDI S tronic',
    year: 2024, segment: 'Premium', bodyType: 'Sedan', color: 'Gümüş',
    shortDescription: 'Premium iç mekân kalitesi ve dengeli dizel performansıyla iş seyahatlerinin tercihi.',
    description: 'Audi A4, malzeme kalitesi ve sürüş dinamikleriyle premium sedan sınıfının referans modellerinden biridir. S tronic şanzıman, yumuşak vites geçişleriyle uzun yolda yorulmayan bir sürüş sağlar.',
    seatCount: 5, doorCount: 4, trunkCapacity: 460,
    fuelType: 'Dizel', transmission: 'Otomatik', gearCount: 7, driveType: 'Önden Çekiş',
    engine: '2.0 TDI', engineVolume: 1968, enginePower: 163, torque: 370, acceleration: 8.2, topSpeed: 232,
    fuelConsumption: 4.9, tankCapacity: 54, emissionClass: 'Euro 6D', co2Emission: 129,
    lengthMm: 4762, widthMm: 1847, heightMm: 1428, curbWeight: 1585,
    safetyFeatures: lines(STD_SAFETY, 'Şerit takip', 'Kör nokta asistanı', 'Ön çarpışma uyarısı'),
    techFeatures: lines(STD_TECH, 'MMI navigasyon', 'Audi virtual cockpit', 'Kablosuz şarj'),
    comfortFeatures: lines('3 bölgeli klima', 'Elektrikli ve hafızalı koltuklar', 'Isıtmalı koltuklar', 'Adaptif hız sabitleyici'),
    exteriorFeatures: lines('LED farlar', '18" alaşım jant', 'Panoramik cam tavan'),
    hasAirConditioning: true, hasNavigation: true, hasReverseCamera: true, hasParkingSensor: true,
    hasCruiseControl: true, hasLeatherSeats: true, hasSunroof: true,
    dailyPrice: 4600, weeklyPrice: 29000, monthlyPrice: 99000, deposit: 20000, extraKmPrice: 17,
    dailyKmLimit: 300, minDriverAge: 28, minLicenseYears: 4, minimumRentalDays: 2,
    featured: true, sortOrder: 7, rating: 4.8, reviewCount: 11,
    mainImage: art('audi-a4'),
  },
  {
    categorySlug: 'araba', name: 'BMW 320i', slug: 'bmw-320i', brand: 'BMW', model: '3 Serisi', version: 'M Sport 320i Steptronic',
    year: 2025, badge: 'PREMIUM', segment: 'Premium', bodyType: 'Sedan', color: 'Siyah',
    shortDescription: 'Arkadan itişli şasi ve M Sport donanımıyla sürüş keyfini öne çıkaran premium sedan.',
    description: 'BMW 3 Serisi, arkadan itişli mimarisi ve dengeli ağırlık dağılımıyla sınıfının en dinamik modellerinden biridir. M Sport donanım paketi, hem iç mekânda hem dış tasarımda sportif bir karakter sunar.',
    seatCount: 5, doorCount: 4, trunkCapacity: 480,
    fuelType: 'Benzin', transmission: 'Otomatik', gearCount: 8, driveType: 'Arkadan İtiş',
    engine: '2.0 TwinPower Turbo', engineVolume: 1998, enginePower: 184, torque: 300, acceleration: 7.1, topSpeed: 240,
    fuelConsumption: 6.5, tankCapacity: 59, emissionClass: 'Euro 6D', co2Emission: 148,
    lengthMm: 4713, widthMm: 1827, heightMm: 1440, curbWeight: 1545,
    safetyFeatures: lines(STD_SAFETY, 'Şerit değiştirme uyarısı', 'Ön çarpışma uyarısı', 'Sürüş asistanı'),
    techFeatures: lines(STD_TECH, 'BMW Live Cockpit navigasyon', 'Head-up display', 'Kablosuz şarj', 'Harman Kardon ses sistemi'),
    comfortFeatures: lines('3 bölgeli klima', 'Elektrikli ve hafızalı koltuk', 'Isıtmalı koltuklar', 'Adaptif hız sabitleyici', 'Ambiyans aydınlatma'),
    exteriorFeatures: lines('Adaptif LED farlar', '19" M alaşım jant', 'M aerodinamik paket'),
    hasAirConditioning: true, hasNavigation: true, hasReverseCamera: true, hasParkingSensor: true,
    hasCruiseControl: true, hasLeatherSeats: true,
    dailyPrice: 5400, weeklyPrice: 34000, monthlyPrice: 115000, deposit: 25000, extraKmPrice: 20,
    dailyKmLimit: 250, minDriverAge: 30, minLicenseYears: 5, minimumRentalDays: 2,
    insuranceInfo: 'Kasko ve trafik sigortası dahildir. Premium sınıfta muafiyet 25.000 ₺ olarak uygulanır.',
    cancellationPolicy: 'Premium sınıf araçlarda iptal talebi kiralama başlangıcından en az 48 saat önce iletilmelidir.',
    featured: true, sortOrder: 8, rating: 4.9, reviewCount: 14,
    mainImage: art('bmw-320i'), seoTitle: 'Kiralık BMW 320i M Sport | Premium Araç Kiralama',
  },
  {
    categorySlug: 'araba', name: 'Mercedes-Benz E 200', slug: 'mercedes-e200', brand: 'Mercedes-Benz', model: 'E Serisi', version: 'Exclusive E 200 9G-TRONIC',
    year: 2025, badge: 'VIP', segment: 'VIP', bodyType: 'Sedan', color: 'Siyah',
    shortDescription: 'VIP transfer ve üst düzey misafir ağırlama için sessiz, konforlu ve prestijli sedan.',
    description: 'Mercedes-Benz E Serisi, sessiz kabini ve yüksek sürüş konforuyla VIP transferlerin standardıdır. Arka koltuk diz mesafesi ve donanım seviyesi, uzun mesafeli transferlerde bile yorgunluk hissettirmez.',
    highlightText: 'Şoförlü kullanım talepleriniz için ayrıca bilgi alabilirsiniz; kurumsal etkinlik ve havalimanı transferlerinde günlük paket seçenekleri sunulmaktadır.',
    seatCount: 5, doorCount: 4, trunkCapacity: 540,
    fuelType: 'Benzin', transmission: 'Otomatik', gearCount: 9, driveType: 'Arkadan İtiş',
    engine: '2.0 Turbo (mild hybrid)', engineVolume: 1999, enginePower: 204, torque: 320, acceleration: 7.5, topSpeed: 240,
    fuelConsumption: 7.1, tankCapacity: 66, emissionClass: 'Euro 6D', co2Emission: 161,
    lengthMm: 4949, widthMm: 1880, heightMm: 1468, curbWeight: 1680,
    safetyFeatures: lines(STD_SAFETY, 'Aktif fren asistanı', 'Kör nokta asistanı', 'Şerit koruma asistanı', 'PRE-SAFE sistemi'),
    techFeatures: lines(STD_TECH, 'MBUX navigasyon', 'Sesli asistan', 'Kablosuz şarj', 'Burmester ses sistemi'),
    comfortFeatures: lines('4 bölgeli klima', 'Elektrikli ve hafızalı koltuklar', 'Isıtmalı ve havalandırmalı koltuklar', 'Arka güneşlik', 'Ambiyans aydınlatma'),
    exteriorFeatures: lines('DIGITAL LIGHT farlar', '18" alaşım jant', 'Panoramik cam tavan'),
    hasAirConditioning: true, hasNavigation: true, hasReverseCamera: true, hasParkingSensor: true,
    hasCruiseControl: true, hasLeatherSeats: true, hasSunroof: true,
    dailyPrice: 7200, weeklyPrice: 45000, monthlyPrice: 152000, deposit: 35000, extraKmPrice: 26,
    dailyKmLimit: 250, minDriverAge: 30, minLicenseYears: 5, minimumRentalDays: 2,
    featured: true, sortOrder: 9, rating: 5, reviewCount: 9,
    mainImage: art('mercedes-e200'),
  },
  {
    categorySlug: 'araba', name: 'Tesla Model 3', slug: 'tesla-model-3', brand: 'Tesla', model: 'Model 3', version: 'Long Range AWD',
    year: 2025, badge: 'ELEKTRİKLİ', segment: 'Premium', bodyType: 'Sedan', color: 'Kırmızı',
    shortDescription: 'Tam elektrikli, 600 km üzeri menzil ve çok düşük kilometre maliyeti.',
    description: 'Tesla Model 3 Long Range, çift motorlu dört tekerlekten çekiş sistemi ve yüksek menziliyle elektrikli araç deneyimini uzun yola taşır. Sessiz sürüş ve düşük enerji maliyeti, yoğun kullanımda belirgin avantaj sağlar.',
    highlightText: 'Şarj planlaması için rota üzerindeki hızlı şarj noktalarını teslim sırasında birlikte gözden geçiriyoruz.',
    seatCount: 5, doorCount: 4, trunkCapacity: 594,
    fuelType: 'Hibrit', transmission: 'Otomatik', driveType: '4x4',
    engine: 'Çift elektrik motoru', enginePower: 366, torque: 493, acceleration: 4.4, topSpeed: 201,
    batteryCapacity: 75, electricRange: 629, chargeTime: 'DC hızlı şarj ile %10-80 yaklaşık 27 dakika',
    emissionClass: 'Sıfır emisyon', co2Emission: 0,
    lengthMm: 4720, widthMm: 1848, heightMm: 1441, curbWeight: 1823,
    safetyFeatures: lines('Otopilot sürüş asistanı', '8 kameralı çevre görüşü', 'Otomatik acil frenleme', 'Şerit koruma', 'Kör nokta uyarısı', 'ISOFIX bağlantı'),
    techFeatures: lines('15" dokunmatik ekran', 'Kablosuz yazılım güncellemesi', 'Navigasyon ve şarj planlayıcı', 'Telefonla anahtarsız erişim', 'Kablosuz şarj'),
    comfortFeatures: lines('Çift bölgeli klima', 'Isıtmalı ön ve arka koltuklar', 'Elektrikli koltuk ayarı', 'Cam tavan'),
    exteriorFeatures: lines('19" alaşım jant', 'Panoramik cam tavan', 'Gizli kapı kolları'),
    hasAirConditioning: true, hasNavigation: true, hasReverseCamera: true, hasParkingSensor: true,
    hasCruiseControl: true, hasLeatherSeats: true, hasSunroof: true,
    dailyPrice: 5800, weeklyPrice: 36500, monthlyPrice: 124000, deposit: 25000, extraKmPrice: 18,
    dailyKmLimit: 300, minDriverAge: 27, minLicenseYears: 3, minimumRentalDays: 2,
    fuelPolicy: 'Araç %80 şarj ile teslim edilir; iade sırasında en az %50 şarj beklenir.',
    featured: true, showOnHomepage: true, sortOrder: 10, rating: 4.8, reviewCount: 21,
    mainImage: art('tesla-model-3'), seoTitle: 'Kiralık Tesla Model 3 | Elektrikli Araç Kiralama',
  },
  {
    categorySlug: 'araba', name: 'Škoda Superb Combi', slug: 'skoda-superb', brand: 'Škoda', model: 'Superb', version: 'Premium 2.0 TDI DSG Combi',
    year: 2024, segment: 'Üst Sınıf', bodyType: 'Station Wagon', color: 'Lacivert',
    shortDescription: '660 litrelik bagajıyla ekip ve ekipman taşımada sınıfının en pratik seçeneği.',
    description: 'Škoda Superb Combi, station wagon gövdesiyle binek araç konforunu yüksek yükleme kapasitesiyle birleştirir. Saha ekipleri ve ekipman taşıyan işletmeler için sedan alternatiflerine göre belirgin avantaj sağlar.',
    seatCount: 5, doorCount: 5, trunkCapacity: 660, luggageCapacity: 'Koltuklar yatırıldığında 1.950 L',
    fuelType: 'Dizel', transmission: 'Otomatik', gearCount: 7, driveType: 'Önden Çekiş',
    engine: '2.0 TDI', engineVolume: 1968, enginePower: 150, torque: 360, acceleration: 9.2, topSpeed: 218,
    fuelConsumption: 5.1, tankCapacity: 66, emissionClass: 'Euro 6D', co2Emission: 134,
    lengthMm: 4862, widthMm: 1864, heightMm: 1477, curbWeight: 1615,
    safetyFeatures: lines(STD_SAFETY, 'Şerit takip', 'Kör nokta uyarısı', 'Yorgunluk tespiti'),
    techFeatures: lines(STD_TECH, 'Navigasyon', 'Dijital gösterge'),
    comfortFeatures: lines('3 bölgeli klima', 'Elektrikli bagaj kapağı', 'Isıtmalı koltuklar', 'Adaptif hız sabitleyici'),
    exteriorFeatures: lines('LED farlar', '18" alaşım jant', 'Tavan rayları'),
    hasAirConditioning: true, hasNavigation: true, hasReverseCamera: true, hasParkingSensor: true, hasCruiseControl: true,
    dailyPrice: 3200, weeklyPrice: 20000, monthlyPrice: 70000, deposit: 12000, extraKmPrice: 12,
    dailyKmLimit: 350, minDriverAge: 25, minLicenseYears: 2,
    showOnHomepage: true, sortOrder: 11, rating: 4.7, reviewCount: 13,
    mainImage: art('skoda-superb'),
  },

  /* ------------------------------------------------------------- SUV */
  {
    categorySlug: 'araba', name: 'Peugeot 2008', slug: 'peugeot-2008', brand: 'Peugeot', model: '2008', version: 'Allure 1.2 PureTech EAT8',
    year: 2025, segment: 'Orta Sınıf', bodyType: 'Crossover', color: 'Antrasit',
    shortDescription: 'Kompakt crossover gövdesiyle şehirde pratik, uzun yolda konforlu.',
    description: 'Peugeot 2008, yüksek sürüş pozisyonunu kompakt boyutlarla birleştirir. i-Cockpit iç tasarımı ve EAT8 otomatik şanzımanı, günlük kullanımda konforlu bir deneyim sunar.',
    seatCount: 5, doorCount: 5, trunkCapacity: 434,
    fuelType: 'Benzin', transmission: 'Otomatik', gearCount: 8, driveType: 'Önden Çekiş',
    engine: '1.2 PureTech', engineVolume: 1199, enginePower: 130, torque: 230, acceleration: 9.1, topSpeed: 206,
    fuelConsumption: 5.9, tankCapacity: 44, emissionClass: 'Euro 6D', co2Emission: 133,
    lengthMm: 4300, widthMm: 1770, heightMm: 1550, curbWeight: 1265,
    safetyFeatures: lines(STD_SAFETY, 'Şerit takip', 'Kör nokta uyarısı'),
    techFeatures: lines(STD_TECH, 'Navigasyon', '3D dijital gösterge'),
    comfortFeatures: lines('Çift bölgeli klima', 'Geri görüş kamerası', 'Adaptif hız sabitleyici', 'Anahtarsız giriş'),
    exteriorFeatures: lines('LED farlar', '17" alaşım jant', 'Tavan rayları'),
    hasAirConditioning: true, hasNavigation: true, hasReverseCamera: true, hasParkingSensor: true, hasCruiseControl: true,
    dailyPrice: 2600, weeklyPrice: 16400, monthlyPrice: 57000, deposit: 9000, extraKmPrice: 10,
    dailyKmLimit: 300, minDriverAge: 24, minLicenseYears: 2,
    featured: true, showOnHomepage: true, sortOrder: 12, rating: 4.6, reviewCount: 17,
    mainImage: art('peugeot-2008'),
  },
  {
    categorySlug: 'araba', name: 'Nissan Qashqai e-Power', slug: 'nissan-qashqai', brand: 'Nissan', model: 'Qashqai', version: 'Tekna e-Power',
    year: 2025, badge: 'HİBRİT', segment: 'Üst Sınıf', bodyType: 'SUV', color: 'Beyaz',
    shortDescription: 'Elektrikli sürüş hissi veren e-Power sistemiyle SUV konforu ve düşük tüketim.',
    description: 'Nissan Qashqai e-Power sisteminde tekerlekleri yalnızca elektrik motoru tahrik eder; benzinli ünite jeneratör olarak çalışır. Sonuç, elektrikli araç sürüş hissi ile şarj derdi olmayan bir kullanım deneyimidir.',
    seatCount: 5, doorCount: 5, trunkCapacity: 455,
    fuelType: 'Hibrit', transmission: 'Otomatik', driveType: 'Önden Çekiş',
    engine: '1.5 VC-Turbo e-Power', engineVolume: 1497, enginePower: 190, torque: 330, acceleration: 7.9, topSpeed: 170,
    fuelConsumption: 5.3, tankCapacity: 55, emissionClass: 'Euro 6D', co2Emission: 119,
    lengthMm: 4425, widthMm: 1835, heightMm: 1625, curbWeight: 1660,
    safetyFeatures: lines(STD_SAFETY, 'ProPILOT sürüş asistanı', 'Kör nokta müdahalesi', '360° kamera'),
    techFeatures: lines(STD_TECH, 'Navigasyon', 'Head-up display', 'Bose ses sistemi'),
    comfortFeatures: lines('Çift bölgeli klima', 'Isıtmalı direksiyon ve koltuklar', 'Elektrikli bagaj kapağı', 'Anahtarsız giriş'),
    exteriorFeatures: lines('Matrix LED farlar', '19" alaşım jant', 'Panoramik cam tavan'),
    hasAirConditioning: true, hasNavigation: true, hasReverseCamera: true, hasParkingSensor: true,
    hasCruiseControl: true, hasSunroof: true, hasLeatherSeats: true,
    dailyPrice: 3400, weeklyPrice: 21500, monthlyPrice: 75000, deposit: 12000, extraKmPrice: 12,
    dailyKmLimit: 300, minDriverAge: 25, minLicenseYears: 2,
    featured: true, showOnHomepage: true, sortOrder: 13, rating: 4.8, reviewCount: 12,
    mainImage: art('nissan-qashqai'),
  },

  /* ------------------------------------------------- HAFİF TİCARİ */
  {
    categorySlug: 'ticari', name: 'Fiat Doblo Cargo', slug: 'fiat-doblo', brand: 'Fiat', model: 'Doblo', version: 'Cargo Maxi 1.5 BlueHDi',
    year: 2024, segment: 'Ticari', bodyType: 'Kamyonet', color: 'Beyaz',
    shortDescription: 'Şehir içi dağıtım ve esnaf kullanımı için ekonomik hafif ticari çözüm.',
    description: 'Fiat Doblo Cargo, kompakt dış ölçüleriyle şehir içi trafikte manevra kolaylığı sağlarken 4,4 m³ yükleme hacmiyle günlük dağıtım operasyonlarını rahatlıkla karşılar. Yan sürgülü kapı, dar alanlarda yükleme kolaylığı sunar.',
    seatCount: 3, doorCount: 4, luggageCapacity: '4,4 m³ yük hacmi · 1.000 kg taşıma kapasitesi',
    fuelType: 'Dizel', transmission: 'Manuel', gearCount: 6, driveType: 'Önden Çekiş',
    engine: '1.5 BlueHDi', engineVolume: 1499, enginePower: 130, torque: 300, acceleration: 12.4, topSpeed: 170,
    fuelConsumption: 5.6, tankCapacity: 61, emissionClass: 'Euro 6D',
    lengthMm: 4753, widthMm: 1848, heightMm: 1812, curbWeight: 1495,
    safetyFeatures: lines('ABS ve EBD', 'ESP', 'Hava yastıkları', 'Yokuş kalkış desteği', 'Geri görüş kamerası'),
    techFeatures: lines('Dokunmatik multimedya', 'Bluetooth', 'USB bağlantı', 'Direksiyondan kumanda'),
    comfortFeatures: lines('Manuel klima', 'Yükseklik ayarlı koltuk', 'Yan sürgülü kapı'),
    exteriorFeatures: lines('Çelik jant', 'Arka çift kanat kapı', 'Yük bölmesi aydınlatması'),
    hasAirConditioning: true, hasBluetooth: true, hasReverseCamera: true, hasIsofix: false,
    dailyPrice: 1750, weeklyPrice: 11000, monthlyPrice: 39000, deposit: 6000, extraKmPrice: 7,
    dailyKmLimit: 350, monthlyKmLimit: 5000, minDriverAge: 23, minLicenseYears: 2,
    deliveryInfo: 'Ticari araçlarda teslimat, iş yeri adresinize planlı şekilde yapılabilir.',
    budgetFriendly: true, showOnHomepage: true, sortOrder: 20, rating: 4.5, reviewCount: 24,
    mainImage: art('fiat-doblo'),
  },
  {
    categorySlug: 'ticari', name: 'Ford Transit Custom', slug: 'ford-transit-custom', brand: 'Ford', model: 'Transit Custom', version: 'Trend L1H1 2.0 EcoBlue',
    year: 2025, segment: 'Ticari', bodyType: 'Panelvan', color: 'Beyaz',
    shortDescription: 'Dengeli yük hacmi ve sürüş konforuyla saha ekiplerinin standart tercihi.',
    description: 'Ford Transit Custom, 6 m³ yükleme hacmi ve binek araca yakın sürüş konforuyla saha ekipleri için ideal bir denge sunar. Yüksek tork değeri, yüklü durumda bile rahat bir sürüş sağlar.',
    seatCount: 3, doorCount: 4, luggageCapacity: '6,0 m³ yük hacmi · 1.100 kg taşıma kapasitesi',
    fuelType: 'Dizel', transmission: 'Manuel', gearCount: 6, driveType: 'Önden Çekiş',
    engine: '2.0 EcoBlue', engineVolume: 1995, enginePower: 136, torque: 390, topSpeed: 165,
    fuelConsumption: 7.2, tankCapacity: 70, emissionClass: 'Euro 6D',
    lengthMm: 4972, widthMm: 1986, heightMm: 1929, curbWeight: 1870,
    safetyFeatures: lines('ABS ve EBD', 'ESP ve yük dengeleme', 'Hava yastıkları', 'Şerit takip', 'Geri görüş kamerası'),
    techFeatures: lines('SYNC multimedya', 'Bluetooth', 'USB bağlantı'),
    comfortFeatures: lines('Manuel klima', 'Hız sabitleyici', 'Katlanabilir orta koltuk'),
    exteriorFeatures: lines('Yan sürgülü kapı', 'Arka çift kanat kapı', 'Yük bölmesi kaplaması'),
    hasAirConditioning: true, hasBluetooth: true, hasReverseCamera: true, hasCruiseControl: true, hasIsofix: false,
    dailyPrice: 2400, weeklyPrice: 15200, monthlyPrice: 53000, deposit: 9000, extraKmPrice: 9,
    dailyKmLimit: 400, monthlyKmLimit: 6000, minDriverAge: 25, minLicenseYears: 2,
    featured: true, showOnHomepage: true, sortOrder: 21, rating: 4.7, reviewCount: 18,
    mainImage: art('ford-transit-custom'),
  },
  {
    categorySlug: 'ticari', name: 'Ford Ranger 4x4', slug: 'ford-ranger', brand: 'Ford', model: 'Ranger', version: 'XLT 2.0 EcoBlue 4x4',
    year: 2024, badge: '4x4', segment: 'Arazi', bodyType: 'Pickup', color: 'Lacivert',
    shortDescription: 'Şantiye ve arazi koşullarında hem yolcu hem yük taşıyan çift kabin pickup.',
    description: 'Ford Ranger, çift kabin yapısıyla beş kişiyi taşırken açık kasasında ekipman naklini mümkün kılar. 4x4 çekiş sistemi, şantiye ve engebeli arazi koşullarında güvenli ilerleme sağlar.',
    seatCount: 5, doorCount: 4, luggageCapacity: 'Açık kasa · 1.000 kg taşıma kapasitesi',
    fuelType: 'Dizel', transmission: 'Otomatik', gearCount: 10, driveType: '4x4',
    engine: '2.0 EcoBlue', engineVolume: 1995, enginePower: 170, torque: 405, topSpeed: 180,
    fuelConsumption: 8.4, tankCapacity: 80, emissionClass: 'Euro 6D',
    lengthMm: 5370, widthMm: 1918, heightMm: 1884, curbWeight: 2250,
    safetyFeatures: lines(STD_SAFETY, 'Yokuş iniş kontrolü', 'Şerit takip', 'Geri görüş kamerası'),
    techFeatures: lines(STD_TECH, 'Navigasyon', 'SYNC 4 multimedya'),
    comfortFeatures: lines('Çift bölgeli klima', 'Isıtmalı koltuklar', 'Hız sabitleyici'),
    exteriorFeatures: lines('17" alaşım jant', 'Kasa kaplaması', 'Çeki demiri', 'Yan basamak'),
    hasAirConditioning: true, hasNavigation: true, hasReverseCamera: true, hasParkingSensor: true, hasCruiseControl: true,
    dailyPrice: 3600, weeklyPrice: 22800, monthlyPrice: 79000, deposit: 15000, extraKmPrice: 14,
    dailyKmLimit: 350, minDriverAge: 26, minLicenseYears: 3,
    sortOrder: 22, rating: 4.7, reviewCount: 8,
    mainImage: art('ford-ranger'),
  },

  /* ------------------------------------------------- BÜYÜK TİCARİ */
  {
    categorySlug: 'ticari', name: 'Ford Transit Jumbo', slug: 'ford-transit-jumbo', brand: 'Ford', model: 'Transit', version: 'Jumbo L4H3 2.0 EcoBlue',
    year: 2024, segment: 'Ticari', bodyType: 'Panelvan', color: 'Beyaz',
    shortDescription: '15,1 m³ yükleme hacmiyle taşınma ve toplu sevkiyatın en pratik çözümü.',
    description: 'Ford Transit Jumbo, uzun şasi ve yüksek tavan yapısıyla 15,1 m³ yükleme hacmi sunar. Ev taşıma, mobilya nakli ve toplu sevkiyat operasyonlarında tek seferde çok daha fazla yük taşımanızı sağlar.',
    seatCount: 3, doorCount: 4, luggageCapacity: '15,1 m³ yük hacmi · 1.400 kg taşıma kapasitesi',
    fuelType: 'Dizel', transmission: 'Manuel', gearCount: 6, driveType: 'Arkadan İtiş',
    engine: '2.0 EcoBlue', engineVolume: 1995, enginePower: 170, torque: 405, topSpeed: 160,
    fuelConsumption: 8.9, tankCapacity: 80, emissionClass: 'Euro 6D',
    lengthMm: 6704, widthMm: 2059, heightMm: 2784, curbWeight: 2380,
    safetyFeatures: lines('ABS ve EBD', 'ESP ve yük dengeleme', 'Hava yastıkları', 'Geri görüş kamerası', 'Yokuş kalkış desteği'),
    techFeatures: lines('SYNC multimedya', 'Bluetooth', 'USB bağlantı'),
    comfortFeatures: lines('Manuel klima', 'Hız sabitleyici', 'Yükseklik ayarlı koltuk'),
    exteriorFeatures: lines('Yan sürgülü kapı', 'Arka 270° açılır kapı', 'Yük bağlama halkaları'),
    hasAirConditioning: true, hasBluetooth: true, hasReverseCamera: true, hasCruiseControl: true, hasIsofix: false,
    dailyPrice: 3100, weeklyPrice: 19600, monthlyPrice: 68000, deposit: 12000, extraKmPrice: 11,
    dailyKmLimit: 400, minDriverAge: 26, minLicenseYears: 3,
    featured: true, showOnHomepage: true, sortOrder: 30, rating: 4.6, reviewCount: 15,
    mainImage: art('ford-transit-jumbo'),
  },
  {
    categorySlug: 'ticari', name: 'Mercedes-Benz Sprinter', slug: 'mercedes-sprinter', brand: 'Mercedes-Benz', model: 'Sprinter', version: '316 CDI Uzun Şasi',
    year: 2025, segment: 'Ticari', bodyType: 'Panelvan', color: 'Beyaz',
    shortDescription: 'Uzun mesafe nakliyede konfor, güvenlik ve yüksek hacmi birleştirir.',
    description: 'Mercedes-Benz Sprinter, uzun mesafe nakliyede sürücü konforu ve güvenlik donanımlarıyla öne çıkar. 14 m³ yükleme hacmi ve yüksek tork değeri, yüklü durumda dahi rahat bir sürüş sunar.',
    seatCount: 3, doorCount: 4, luggageCapacity: '14,0 m³ yük hacmi · 1.500 kg taşıma kapasitesi',
    fuelType: 'Dizel', transmission: 'Otomatik', gearCount: 9, driveType: 'Arkadan İtiş',
    engine: '2.0 CDI', engineVolume: 1950, enginePower: 163, torque: 380, topSpeed: 160,
    fuelConsumption: 8.5, tankCapacity: 71, emissionClass: 'Euro 6D',
    lengthMm: 6967, widthMm: 2020, heightMm: 2695, curbWeight: 2450,
    safetyFeatures: lines('ABS ve EBD', 'ESP ve rüzgâr asistanı', 'Aktif fren asistanı', 'Şerit koruma', 'Geri görüş kamerası'),
    techFeatures: lines('MBUX multimedya', 'Navigasyon', 'Bluetooth', 'USB-C bağlantı'),
    comfortFeatures: lines('Otomatik klima', 'Hız sabitleyici', 'Konfor sürücü koltuğu'),
    exteriorFeatures: lines('Yan sürgülü kapı', 'Arka 270° açılır kapı', 'Yük bölmesi kaplaması'),
    hasAirConditioning: true, hasNavigation: true, hasReverseCamera: true, hasCruiseControl: true, hasIsofix: false,
    dailyPrice: 3800, weeklyPrice: 24000, monthlyPrice: 83000, deposit: 15000, extraKmPrice: 13,
    dailyKmLimit: 400, minDriverAge: 26, minLicenseYears: 3,
    sortOrder: 31, rating: 4.8, reviewCount: 10,
    mainImage: art('mercedes-sprinter'),
  },

  /* -------------------------------------------------- MOTOSİKLET */
  {
    categorySlug: 'motor', name: 'Honda CBF 250', slug: 'honda-cbf-250', brand: 'Honda', model: 'CBF 250', version: 'Twister',
    year: 2024, segment: 'Ekonomik', bodyType: 'Motosiklet', color: 'Kırmızı',
    shortDescription: 'Şehir içi ulaşımda ekonomik, hafif ve kullanımı kolay motosiklet.',
    description: 'Honda CBF 250, düşük ağırlığı ve dengeli sürüş karakteriyle şehir içi kullanımda pratik bir çözümdür. Düşük yakıt tüketimi sayesinde günlük ulaşım maliyetini belirgin şekilde azaltır.',
    seatCount: 2, fuelType: 'Benzin', transmission: 'Manuel', gearCount: 5, driveType: 'Arkadan İtiş',
    engine: '250 cc tek silindir', engineVolume: 249, enginePower: 23, torque: 20, topSpeed: 130,
    fuelConsumption: 2.6, tankCapacity: 16, emissionClass: 'Euro 5',
    curbWeight: 148,
    safetyFeatures: lines('ABS fren sistemi', 'Disk fren (ön/arka)', 'Kask dahildir'),
    comfortFeatures: lines('Dijital gösterge', 'USB şarj çıkışı'),
    exteriorFeatures: lines('LED far', 'Yan kutu bağlantı noktası'),
    hasAirConditioning: false, hasIsofix: false, hasBluetooth: false,
    dailyPrice: 750, weeklyPrice: 4500, monthlyPrice: 15000, deposit: 3000,
    dailyKmLimit: 200, minDriverAge: 21, minLicenseYears: 1,
    insuranceInfo: 'Zorunlu trafik sigortası dahildir. Kask ve koruyucu ekipman kiralamaya dahildir.',
    deliveryInfo: 'Motosikletler ofisimizden teslim alınır; şehir içi teslimat ek ücrete tabidir.',
    budgetFriendly: true, showOnHomepage: true, sortOrder: 40, rating: 4.4, reviewCount: 26,
    mainImage: art('honda-cbf-250'), cityDeliveryFree: false,
  },
  {
    categorySlug: 'motor', name: 'Yamaha MT-07', slug: 'yamaha-mt-07', brand: 'Yamaha', model: 'MT-07', version: 'ABS',
    year: 2025, segment: 'Orta Sınıf', bodyType: 'Motosiklet', color: 'Lacivert',
    shortDescription: 'Güçlü çift silindirli motoruyla şehir ve gezi sürüşlerinin popüler naked modeli.',
    description: 'Yamaha MT-07, 689 cc çift silindirli motoru ve düşük ağırlığıyla hem şehir içinde hem gezi sürüşlerinde keyifli bir deneyim sunar. A2 üstü ehliyet gerektirir.',
    seatCount: 2, fuelType: 'Benzin', transmission: 'Manuel', gearCount: 6, driveType: 'Arkadan İtiş',
    engine: '689 cc CP2 çift silindir', engineVolume: 689, enginePower: 73, torque: 67, acceleration: 3.7, topSpeed: 205,
    fuelConsumption: 4.3, tankCapacity: 14, emissionClass: 'Euro 5',
    curbWeight: 184,
    safetyFeatures: lines('ABS fren sistemi', 'Çift disk ön fren', 'Kask ve koruyucu ekipman dahildir'),
    techFeatures: lines('Tam dijital LCD gösterge'),
    exteriorFeatures: lines('LED far ve stop', 'Sportif egzoz'),
    hasAirConditioning: false, hasIsofix: false, hasBluetooth: false,
    dailyPrice: 1600, weeklyPrice: 9600, monthlyPrice: 32000, deposit: 8000,
    dailyKmLimit: 250, minDriverAge: 24, minLicenseYears: 2, minimumRentalDays: 1,
    insuranceInfo: 'Zorunlu trafik sigortası dahildir. A sınıfı ehliyet ve en az 2 yıl deneyim gereklidir.',
    featured: true, sortOrder: 41, rating: 4.9, reviewCount: 12,
    mainImage: art('yamaha-mt-07'), cityDeliveryFree: false,
  },
  {
    categorySlug: 'motor', name: 'Vespa Primavera 125', slug: 'vespa-primavera', brand: 'Vespa', model: 'Primavera', version: '125 i-get',
    year: 2024, segment: 'Ekonomik', bodyType: 'Scooter', color: 'Yeşil',
    shortDescription: 'Şehir içi kısa mesafeler için şık, kolay kullanımlı ve otomatik scooter.',
    description: 'Vespa Primavera 125, otomatik şanzımanı ve düşük ağırlığıyla şehir içi kısa mesafelerde kullanımı en kolay seçeneklerden biridir. Kask saklama gözü ve düz platform yapısı günlük pratiklik sağlar.',
    seatCount: 2, fuelType: 'Benzin', transmission: 'Otomatik', driveType: 'Arkadan İtiş',
    engine: '125 cc i-get', engineVolume: 124, enginePower: 11, torque: 10, topSpeed: 91,
    fuelConsumption: 2.2, tankCapacity: 8, emissionClass: 'Euro 5',
    curbWeight: 114,
    safetyFeatures: lines('ABS ön fren', 'Kask dahildir'),
    comfortFeatures: lines('Kask saklama gözü', 'Düz ayak platformu', 'USB şarj çıkışı'),
    exteriorFeatures: lines('LED far', 'Çelik gövde'),
    hasAirConditioning: false, hasIsofix: false, hasBluetooth: false,
    dailyPrice: 650, weeklyPrice: 3900, monthlyPrice: 13000, deposit: 3000,
    dailyKmLimit: 150, minDriverAge: 20, minLicenseYears: 1,
    budgetFriendly: true, sortOrder: 42, rating: 4.5, reviewCount: 20,
    mainImage: art('vespa-primavera'), cityDeliveryFree: false,
  },

  /* ------------------------------------------------------- TEKNE */
  {
    categorySlug: 'tekne', name: 'Sea Ray 230 SLX', slug: 'sea-ray-230', brand: 'Sea Ray', model: '230 SLX', version: 'Bowrider',
    year: 2023, badge: 'POPÜLER', segment: 'Deniz Aracı', bodyType: 'Tekne', color: 'Beyaz',
    shortDescription: 'Sekiz kişilik kapasitesiyle günübirlik koy turlarının favori sürat teknesi.',
    description: 'Sea Ray 230 SLX, geniş ön oturma alanı ve güneşlenme platformuyla günübirlik koy turları için tasarlanmıştır. Sekiz kişiye kadar konforlu kullanım sunar; can yeleği ve temel güvenlik ekipmanı kiralamaya dahildir.',
    highlightText: 'Kaptanlı kullanım tercih edilebilir. Kaptansız kullanım için amatör denizci belgesi (ADB) zorunludur.',
    seatCount: 8, fuelType: 'Benzin', driveType: 'Arkadan İtiş',
    engine: '250 HP MerCruiser', enginePower: 250, topSpeed: 74, tankCapacity: 190,
    lengthMm: 7010, widthMm: 2590, curbWeight: 2100,
    safetyFeatures: lines('Can yelekleri (8 adet)', 'Yangın söndürücü', 'İlk yardım çantası', 'Can simidi', 'Telsiz'),
    comfortFeatures: lines('Güneşlenme platformu', 'Bluetooth ses sistemi', 'Soğutucu bölme', 'Duş', 'Yüzme merdiveni'),
    exteriorFeatures: lines('Bimini tente', 'Teak güverte kaplaması'),
    hasAirConditioning: false, hasIsofix: false, hasBluetooth: true,
    dailyPrice: 18000, weeklyPrice: 108000, deposit: 25000, showPrice: true,
    minimumRentalDays: 1, minDriverAge: 25, minLicenseYears: 0,
    insuranceInfo: 'Tekne sigortası dahildir. Kaptansız kullanımda amatör denizci belgesi (ADB) zorunludur.',
    fuelPolicy: 'Yakıt kiralama bedeline dahil değildir; kullanım sonunda ölçülerek faturalandırılır.',
    deliveryInfo: 'Teslim noktası marina içinde belirlenir; buluşma saati rezervasyonla netleştirilir.',
    cancellationPolicy: 'Olumsuz hava koşullarında kiralama ücretsiz olarak ertelenir.',
    featured: true, sortOrder: 50, rating: 4.9, reviewCount: 7,
    mainImage: art('sea-ray-230'), cityDeliveryFree: false, hgsIncluded: false,
  },
  {
    categorySlug: 'tekne', name: 'Bayliner VR5', slug: 'bayliner-vr5', brand: 'Bayliner', model: 'VR5', version: 'Bowrider',
    year: 2022, segment: 'Deniz Aracı', bodyType: 'Tekne', color: 'Mavi',
    shortDescription: 'Yedi kişilik kapasitesiyle aile kullanımına uygun ekonomik bowrider.',
    description: 'Bayliner VR5, dengeli gövde yapısı ve pratik kullanımıyla aile gezileri için uygun bir seçenektir. Su sporları ekipmanı çekişine uygun donanıma sahiptir.',
    seatCount: 7, fuelType: 'Benzin', driveType: 'Arkadan İtiş',
    engine: '150 HP Mercury', enginePower: 150, topSpeed: 62, tankCapacity: 120,
    lengthMm: 5900, widthMm: 2440, curbWeight: 1450,
    safetyFeatures: lines('Can yelekleri (7 adet)', 'Yangın söndürücü', 'İlk yardım çantası', 'Can simidi'),
    comfortFeatures: lines('Güneşlenme minderi', 'Bluetooth ses sistemi', 'Yüzme merdiveni'),
    exteriorFeatures: lines('Bimini tente', 'Su sporları çeki demiri'),
    hasAirConditioning: false, hasIsofix: false, hasBluetooth: true,
    dailyPrice: 12000, weeklyPrice: 72000, deposit: 18000,
    minDriverAge: 25,
    insuranceInfo: 'Tekne sigortası dahildir. Kaptansız kullanımda amatör denizci belgesi (ADB) zorunludur.',
    fuelPolicy: 'Yakıt kiralama bedeline dahil değildir.',
    sortOrder: 51, rating: 4.6, reviewCount: 5,
    mainImage: art('bayliner-vr5'), cityDeliveryFree: false, hgsIncluded: false,
  },

  /* ------------------------------------------------------ JETSKİ */
  {
    categorySlug: 'jetski', name: 'Yamaha VX Cruiser', slug: 'yamaha-vx-cruiser', brand: 'Yamaha', model: 'VX Cruiser', version: 'HO',
    year: 2024, segment: 'Deniz Aracı', bodyType: 'Jetski', color: 'Mavi',
    shortDescription: 'Üç kişilik kapasitesi ve dengeli gövdesiyle yeni başlayanlar için ideal.',
    description: 'Yamaha VX Cruiser, geniş oturma alanı ve dengeli gövde yapısıyla jetski deneyimine yeni başlayanlar için güvenli bir seçenektir. Kiralama öncesi temel kullanım eğitimi verilir.',
    seatCount: 3, fuelType: 'Benzin',
    engine: '1812 cc HO', engineVolume: 1812, enginePower: 180, topSpeed: 105, tankCapacity: 70,
    lengthMm: 3350, widthMm: 1230, curbWeight: 372,
    safetyFeatures: lines('Can yeleği dahildir', 'Emniyet kordonu', 'Kullanım eğitimi verilir'),
    comfortFeatures: lines('Üç kişilik oturma alanı', 'Su geçirmez saklama gözü', 'Çekme kancası'),
    hasAirConditioning: false, hasIsofix: false, hasBluetooth: false,
    dailyPrice: 6500, weeklyPrice: 39000, deposit: 10000,
    minDriverAge: 21,
    insuranceInfo: 'Sorumluluk sigortası dahildir. Kullanım öncesi güvenlik brifingi zorunludur.',
    fuelPolicy: 'Yakıt kullanım sonunda ölçülerek faturalandırılır.',
    deliveryInfo: 'Teslim noktası plaj veya marina olarak belirlenir.',
    featured: true, sortOrder: 60, rating: 4.7, reviewCount: 18,
    mainImage: art('yamaha-vx-cruiser'), cityDeliveryFree: false, hgsIncluded: false,
  },
  {
    categorySlug: 'jetski', name: 'Sea-Doo GTI 130', slug: 'seadoo-gti-130', brand: 'Sea-Doo', model: 'GTI', version: '130',
    year: 2023, segment: 'Deniz Aracı', bodyType: 'Jetski', color: 'Turuncu',
    shortDescription: 'Kolay kontrol edilebilir yapısıyla günübirlik deniz keyfi için pratik seçim.',
    description: 'Sea-Doo GTI 130, dengeli gövdesi ve kullanıcı dostu kontrolleriyle günübirlik kiralamalarda tercih edilen bir modeldir. iBR geri vites sistemi, manevra ve yanaşmayı kolaylaştırır.',
    seatCount: 3, fuelType: 'Benzin',
    engine: '1630 cc Rotax', engineVolume: 1630, enginePower: 130, topSpeed: 95, tankCapacity: 60,
    lengthMm: 3300, widthMm: 1220, curbWeight: 349,
    safetyFeatures: lines('Can yeleği dahildir', 'Emniyet kordonu', 'iBR geri vites ve fren sistemi', 'Kullanım eğitimi verilir'),
    comfortFeatures: lines('Üç kişilik oturma alanı', 'Saklama bölmesi'),
    hasAirConditioning: false, hasIsofix: false, hasBluetooth: false,
    dailyPrice: 5500, weeklyPrice: 33000, deposit: 9000,
    minDriverAge: 21,
    fuelPolicy: 'Yakıt kullanım sonunda ölçülerek faturalandırılır.',
    budgetFriendly: true, sortOrder: 61, rating: 4.6, reviewCount: 14,
    mainImage: art('seadoo-gti-130'), cityDeliveryFree: false, hgsIncluded: false,
  },

  /* --------------------------------------------------------- ATV */
  {
    categorySlug: 'atv', name: 'CFMoto CForce 520', slug: 'cfmoto-cforce-520', brand: 'CFMoto', model: 'CForce 520', version: '4x4 EPS',
    year: 2024, segment: 'Arazi', bodyType: 'ATV', color: 'Yeşil',
    shortDescription: '4x4 çekişi ve direksiyon destek sistemiyle arazi sürüşünde dengeli performans.',
    description: 'CFMoto CForce 520, elektrikli direksiyon desteği (EPS) ve seçilebilir 4x4 çekiş sistemiyle engebeli arazide kolay kontrol sağlar. Grup turları ve arazi gezileri için uygundur.',
    seatCount: 2, fuelType: 'Benzin', transmission: 'Otomatik', driveType: '4x4',
    engine: '495 cc tek silindir', engineVolume: 495, enginePower: 40, torque: 42, topSpeed: 90, tankCapacity: 17,
    lengthMm: 2210, widthMm: 1180, heightMm: 1260, curbWeight: 350,
    safetyFeatures: lines('Kask dahildir', 'Disk fren sistemi', 'Kullanım eğitimi verilir'),
    comfortFeatures: lines('Elektrikli direksiyon desteği', 'Ön ve arka yük rafı', 'Dijital gösterge'),
    exteriorFeatures: lines('Çamurluk koruma', 'Vinç bağlantı noktası', 'LED far'),
    hasAirConditioning: false, hasIsofix: false, hasBluetooth: false,
    dailyPrice: 2800, weeklyPrice: 16800, deposit: 7000,
    minDriverAge: 21, dailyKmLimit: 120,
    insuranceInfo: 'Sorumluluk sigortası dahildir. Kask ve koruyucu ekipman kiralamaya dahildir.',
    deliveryInfo: 'ATV araçları belirlenen arazi parkurunda teslim edilir; karayolu kullanımına uygun değildir.',
    featured: true, sortOrder: 70, rating: 4.7, reviewCount: 11,
    mainImage: art('cfmoto-cforce-520'), cityDeliveryFree: false, hgsIncluded: false,
  },
  {
    categorySlug: 'atv', name: 'Polaris Sportsman 570', slug: 'polaris-sportsman-570', brand: 'Polaris', model: 'Sportsman 570', version: 'EPS',
    year: 2023, segment: 'Arazi', bodyType: 'ATV', color: 'Kırmızı',
    shortDescription: 'Yüksek tork ve dayanıklı süspansiyonuyla zorlu arazi koşullarına uygun.',
    description: 'Polaris Sportsman 570, uzun süspansiyon kursu ve yüksek tork değeriyle zorlu arazi koşullarında güçlü performans sunar. Bağımsız arka süspansiyon, engebeli zeminlerde konfor sağlar.',
    seatCount: 1, fuelType: 'Benzin', transmission: 'Otomatik', driveType: '4x4',
    engine: '567 cc ProStar', engineVolume: 567, enginePower: 44, torque: 45, topSpeed: 95, tankCapacity: 17,
    lengthMm: 2130, widthMm: 1220, heightMm: 1230, curbWeight: 315,
    safetyFeatures: lines('Kask dahildir', 'Disk fren sistemi', 'Kullanım eğitimi verilir'),
    comfortFeatures: lines('Elektrikli direksiyon desteği', 'Bağımsız arka süspansiyon', 'Ön ve arka yük rafı'),
    exteriorFeatures: lines('LED far', 'Vinç bağlantı noktası', 'Çeki demiri'),
    hasAirConditioning: false, hasIsofix: false, hasBluetooth: false,
    dailyPrice: 3200, weeklyPrice: 19200, deposit: 8000,
    minDriverAge: 21, dailyKmLimit: 120,
    deliveryInfo: 'ATV araçları belirlenen arazi parkurunda teslim edilir; karayolu kullanımına uygun değildir.',
    sortOrder: 71, rating: 4.8, reviewCount: 6,
    mainImage: art('polaris-sportsman-570'), cityDeliveryFree: false, hgsIncluded: false,
  },
];

/* ------------------------------------------------------------------ */
/*  Çalıştırma                                                         */
/* ------------------------------------------------------------------ */
async function main() {
  console.log('→ Kategoriler yazılıyor…');
  for (const [index, [name, shortName, slug, description, longDescription]] of categories.entries()) {
    await prisma.category.upsert({
      where: { slug },
      update: { name, shortName, description, longDescription, sortOrder: index + 1, isActive: true },
      create: { name, shortName, slug, description, longDescription, sortOrder: index + 1 },
    });
  }

  console.log('→ Araçlar yazılıyor…');
  const categoryIds = new Map<string, string>();
  for (const c of await prisma.category.findMany()) categoryIds.set(c.slug, c.id);

  for (const { categorySlug, gallery, ...data } of vehicles) {
    const categoryId = categoryIds.get(categorySlug);
    if (!categoryId) throw new Error(`Kategori bulunamadı: ${categorySlug}`);

    const payload = { ...data, categoryId } as unknown as Prisma.VehicleUncheckedCreateInput;
    await prisma.vehicle.upsert({
      where: { slug: data.slug },
      update: payload,
      create: payload,
    });

    if (gallery?.length) {
      const vehicle = await prisma.vehicle.findUniqueOrThrow({ where: { slug: data.slug } });
      await prisma.vehicleImage.deleteMany({ where: { vehicleId: vehicle.id } });
      await prisma.vehicleImage.createMany({
        data: gallery.map((imageUrl, sortOrder) => ({ vehicleId: vehicle.id, imageUrl, sortOrder })),
      });
    }
  }

  // Eski kategori yapısından kalan ve artık kullanılmayan kayıtları temizle.
  // Araçlar yukarıda yeni kategorilerine taşındığı için bu işlem veri kaybettirmez.
  await prisma.category.deleteMany({
    where: { slug: { notIn: categories.map(([, , slug]) => slug) }, vehicles: { none: {} } },
  });

  console.log('→ Site ayarları yazılıyor…');
  const settings = {
    siteName: 'Millwal Kurumsal Kiralama',
    companyLegalName: 'MİLLWALL KURUMSAL HİZMETLER LİMİTED ŞİRKETİ',
    phone: '05555555555',
    whatsapp: '905555555555',
    email: 'info@millwal.com.tr',
    address: 'İstasyon Mah. Yarış Çıkmazı Sk. No: 2 İç Kapı No: 219 Tuzla / İstanbul',
    mersisNo: '0621132487300001',
    tradeRegistryNo: '1154685',
    tradeRegistryOffice: 'T.C. İstanbul Ticaret Sicili Müdürlüğü',
    workingHours: 'Pazartesi - Cumartesi 09:00 - 19:00',
    workingHoursWeekend: 'Pazar 10:00 - 16:00 (randevulu)',
    footerDescription:
      'Otomobilden ticari araca, motosikletten deniz araçlarına kadar geniş filomuzla bireysel ve kurumsal kiralama çözümleri sunuyoruz. Koşullar şeffaf, iletişim hızlı.',
    seoTitle: 'Millwal Kurumsal Kiralama | Araç ve Filo Kiralama',
    seoDescription:
      'İstanbul merkezli araç, ticari araç, motosiklet ve deniz aracı kiralama çözümleri. Günlük, haftalık, aylık ve kurumsal uzun dönem seçenekleri.',
    campaignEnabled: true,
    campaignTitle: 'Kurumsal kiralamada size özel çözümler',
    campaignText:
      'İhtiyacınıza uygun aracı birlikte belirleyelim. Hızlı bilgi ve teklif için WhatsApp üzerinden bize ulaşın.',
    campaignImageUrl: '/fleet/volkswagen-passat.jpg',
    campaignButtonText: "WhatsApp'tan Teklif Al",
  };

  await prisma.settings.upsert({ where: { id: 1 }, update: settings, create: { id: 1, ...settings } });

  console.log('→ Yönetici hesabı yazılıyor…');
  const passwordHash = await bcrypt.hash(process.env.ADMIN_SEED_PASSWORD || 'Millwal2026!', 12);
  await prisma.admin.upsert({
    where: { username: 'admin' },
    update: { passwordHash },
    create: {
      name: 'Millwal Yönetici',
      email: 'admin@millwal.com.tr',
      username: 'admin',
      passwordHash,
      role: 'SUPER_ADMIN',
    },
  });

  const count = await prisma.vehicle.count();
  console.log(`✓ Tamamlandı — ${categories.length} kategori, ${count} araç.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
